version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - $(aws ecr get-login --no-include-email --region ${REGION})
  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building the Docker image..."
      - docker build -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} . -f Dockerfile_ecr
      - echo "docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${ECR_REPO_URL}:${IMAGE_TAG}"
      - docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${ECR_REPO_URL}:${IMAGE_TAG}
  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing the Docker image..."
      - docker push ${ECR_REPO_URL}:${IMAGE_TAG}
      - touch dummy.zip

artifacts:
  files: dummy.zip