AWSTemplateFormatVersion: 2010-09-09
Description: ECR Template
Parameters:
  CodeCommitStackName:
    Type: String
Resources:
  EcrRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: test-laravel
      RepositoryPolicyText: 
        Version: 2008-10-17
        Statement: 
          - 
            Sid: CodeBuildAccess
            Effect: Allow
            Principal: 
              Service: 
                - codebuild.amazonaws.com
            Action: 
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
  EcrBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
                - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      RoleName: laravel-ec2-sample-ecr-build
  EcrBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: laravel-ec2-sample-ecr
      ServiceRole: !Ref EcrBuildServiceRole
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: True
        EnvironmentVariables:
          - Name: REGION
            Value: ap-northeast-1
            Type: PLAINTEXT
          - Name: IMAGE_REPO_NAME
            Value: test-laravel
            Type: PLAINTEXT
          - Name: IMAGE_TAG
            Value: latest
            Type: PLAINTEXT
          - Name: ECR_REPO_URL
            Value: !Sub ${AWS::AccountId}.dkr.ecr.ap-northeast-1.amazonaws.com/test-laravel
            Type: PLAINTEXT
      Source:
        Type: CODECOMMIT
        Location:
          Fn::ImportValue: !Sub ${CodeCommitStackName}-CodeCommitRepoCloneUrlHttp
        BuildSpec: buildspec_ecr.yml
